### ISSUE TITLE
선택한 주소표기 방식에 상관없이 지번으로 입력되게 하고있는데요

### ISSUE THREAD

**Issue by cgrking** [daumPostcode/QnA#223]
안녕하세요 아래의 답변을 받아 현재 사용자가 지번/도로명 선택에 상관없이 무조건

지번 주소가 입력되게 사용하고있는데요 

간혹가다가 값이 입력이 안되는 경우가 있더라구요

서울 종로구 송월길 99 (경희궁자이 2단지) 

위의 도로명 주소를 선택하면 ( 검색값으로 나온 지번 주소를 선택해도 마찬가지입니다)

입력 박스에 데이터가 안들어가더라구요 

혹시 해결이 가능할까요?
---------------------------------------------------------------------------------
cgrking2  commented 19 days ago 

자주묻는 FAQ 16번에 위 제목처럼 도로/지번 선택시 무조건 도로명이 넘어가게하는건 있더라구요

혹시 반대로 도로/지번 선택시 무조건 지번으로 입력되게하는것도 있을까요?
 

@daumPostcode  

Owner This user is the owner of the QnA repository. 
daumPostcode  commented 19 days ago 

@cgrking2
네~ 안녕하세요~

저희 서비스에서 내리는 데이터는 지번주소와 도로명주소가 한쌍입니다.
가이드 페이지 oncomplete함수 설명 부분에 내리는 데이터가 정리되어 있습니다,

FAQ16번을 읽어 보셨다면, 거기에는 roadAddress, autoRoadAddress가 언급되어 있죠?
이를 jibunAddress autoJibunAddress로 바꿔서 해석하시면 됩니다.

**Comment by daumPostcode** [comment]
@cgrking 
안녕하세요~

가이드 페이지의 oncomplete 설명 부분에 보시면 반환되는 데이터 확인하기 버튼이 있습니다. 이 버튼을 통해 내려가는 데이터를 확인 하실 수가 있는데요. 

말씀해 주신 주소로 확인해보니;
jibunAddress 또는 autoJibunAddress에 데이터가 할당이 되고 있네요.

oncomplete부분의 구현 로직은 API를 이용하시는 개발자분의 몫입니다. 그렇기 때문에, 현재 제가 확인 할 수 있는 사항은 데이터가 내려가는지의 유무 외에는 알 수가 없습니다.

API의 생성자 코드와, oncomplete의 내부 함수의 코드를 적어주시면 좀 더 확인해 보도록 하겠습니다.

**Comment by cgrking2** [comment]
안녕하세요 확인 부탁드립니다.
 
 
자바스크립트 소스
 
 
var daum_zip_id = function(frm_zipcode, frm_address1, frm_address2,zip_case) {        if (typeof daum === 'undefined') {            alert('다음 juso.js 파일이 로드되지 않았습니다.');            return false;        }  if(zip_case==='undefined')         zip_case = 1;   //0이면 레이어, 1이면 페이지에 끼워 넣기, 2이면 새창
        var complete_fn = function(data){            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
            // 각 주소의 노출 규칙에 따라 주소를 조합한다.            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.            var fullAddr = ''; // 최종 주소 변수            var extraAddr = ''; // 조합형 주소 변수
            // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.      //      if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우       //         fullAddr = data.roadAddress;
       //     } else { // 사용자가 지번 주소를 선택했을 경우(J)               fullAddr =data.jibunAddress;    if(!fullAddr) {     alert('지번 주소를 선택해주세요');         }           //     }
            // 사용자가 선택한 주소가 도로명 타입일때 조합한다.            if (data.userSelectedType === 'R'){                //법정동명이 있을 경우 추가한다.                if (data.bname !== ''){                    extraAddr += data.bname;                }                // 건물명이 있을 경우 추가한다.                if (data.buildingName !== ''){                    extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);                }                // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.                extraAddr = (extraAddr !== '' ? ' (' + extraAddr + ')' : '');            }
            // 우편번호와 주소 정보를 해당 필드에 넣고, 커서를 상세주소 필드로 이동한다.                
            $('#'+frm_zipcode).val(data.zonecode);            $('#'+frm_address1).val(fullAddr);            $('#'+frm_address2).focus();        };
        switch(zip_case) {            case 1 :    //iframe을 이용하여 페이지에 끼워 넣기                var daum_pape_id = 'daum_juso_page' + frm_zipcode,                    element_wrap = document.getElementById(daum_pape_id),                    currentScroll = Math.max(document.body.scrollTop, document.documentElement.scrollTop);                if (element_wrap === null) {                    element_wrap = document.createElement('div');                    element_wrap.setAttribute('id', daum_pape_id);                    element_wrap.style.cssText = 'display:none;border:1px solid;left:0;width:100%;height:300px;margin:5px 0;position:relative;-webkit-overflow-scrolling:touch;';                    element_wrap.innerHTML = '<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnFoldWrap" style="cursor:pointer;position:absolute;right:0px;top:-21px;z-index:1" class="close_daum_juso" alt="접기 버튼">';                    jQuery('#'+frm_address1).before(element_wrap);                    jQuery('#' + daum_pape_id).off('click', '.close_daum_juso').on('click', '.close_daum_juso', function(e){                        e.preventDefault();                        jQuery(this).parent().hide();                    });                }
                new daum.Postcode({                    oncomplete: function(data) {                        complete_fn(data);                        // iframe을 넣은 element를 안보이게 한다.                        element_wrap.style.display = 'none';                        // 우편번호 찾기 화면이 보이기 이전으로 scroll 위치를 되돌린다.                        document.body.scrollTop = currentScroll;                    },                    // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분.                    // iframe을 넣은 element의 높이값을 조정한다.                    onresize : function(size) {                        element_wrap.style.height = size.height + 'px';                    },                    width : '100%',                    height : '100%'                }).embed(element_wrap);
                // iframe을 넣은 element를 보이게 한다.                element_wrap.style.display = 'block';                break;            case 2 :    //새창으로 띄우기                new daum.Postcode({                    oncomplete: function(data) {                        complete_fn(data);                    }                }).open();                break;            default :   //iframe을 이용하여 레이어 띄우기                var rayer_id = 'daum_juso_rayer' + frm_zipcode,                    element_layer = document.getElementById(rayer_id);                if (element_layer === null) {                    element_layer = document.createElement('div');                    element_layer.setAttribute('id', rayer_id);                    element_layer.style.cssText = 'display:none;border:5px solid;position:fixed;width:300px;height:460px;left:50%;margin-left:-155px;top:50%;margin-top:-235px;overflow:hidden;-webkit-overflow-scrolling:touch;z-index:10000';                    element_layer.innerHTML = '<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" class="close_daum_juso" alt="닫기 버튼">';                    document.body.appendChild(element_layer);                    jQuery('#' + rayer_id).off('click', '.close_daum_juso').on('click', '.close_daum_juso', function(e){                        e.preventDefault();                        jQuery(this).parent().hide();                    });                }
                new daum.Postcode({                    oncomplete: function(data) {                        complete_fn(data);                        // iframe을 넣은 element를 안보이게 한다.                        element_layer.style.display = 'none';                    },                    width : '100%',                    height : '100%'                }).embed(element_layer);
                // iframe을 넣은 element를 보이게 한다.                element_layer.style.display = 'block';        }    }
 
 
 
function changeAddr(){ $('#addr').hide(); $('#newaddr').show(); daum_zip_id( 'zip', 'addr1_id', 'addr2', 2);}
 
 
 
html 소스 
 
 
<tr >             <th scope="row">주소 <a  href="javascript:changeAddr()" class="btLightG">주소변경</a></th>             <td><div id=addr><?=stripslashes($mem[addr])?></div>              <div id=newaddr style='display:none' >               <input type=text size=5 name=zip id=zip placeholder='우편번호' maxlength=5 readonly>               <input type=text size=30 name='addr1_id' id='addr1_id' placeholder='기본주소' readonly>               <input type=text size=20 name=addr2 id=addr2 placeholder='상세주소'>               <button onclick="changeAddrSubmit()" style='height:25px;line-height:15px;padding:2px ;border:1px solid gray;border-radius: 15px;'>변경하기 </button>                             </div></td>  </tr>
 
 

   
  최가람 경영지원 팀 / 매니저
                 tel. 02 6012 9215
                 e-mail. cgrking@englishegg.co.kr
  http://www.englishegg.co.kr    
 
 



이 전자 메일에 포함 된 정보와 함께 문서는 법적으로 보호받는 기밀 정보 사항을 포함 할 수 있습니다. 이 전자 메일을 정당하게 받는 사람이 아닌 경우, 또는 이 메시지가 잘못된 주소로 되어 있는 경우, 즉시 발신자에게 전자 메일로 경고를 한 후 모든 첨부 파일을 포함한 메시지를 삭제하시기 바랍니다. 정당하게 받는 사람 이외의 다른 사람에 의해 이 메시지의 내용이 보급, 배포 또는 다른 용도로의 사용되는 것은 엄격하게 금지됩니다. 내부 정책을 준수하고 우리는 우리의 비즈니스를 보호하기 위해 법률 및 규정에서 허용하는 내에서 이 전자 메일 주소에서 발송되는 모든 전자 메일을 모니터링 할 수 있습니다. 본 전자 메일은 안전을 보장할 수 없으며, 전자메일의 내용이 개정, 분실 또는 파괴 될 수 있고 또한 바이러스가 포함 될 수 있습니다. 당신은 이 전자 메일을 통해 당사자와 의사 소통을하는 경우 그 위험을 수락 한 것으로 간주됨을 알려드립니다. The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited. All messages sent to and from this e-mail address may be monitored as permitted by applicable law and regulations to ensure compliance with our internal policies and to protect our business. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, lost or destroyed, or contain viruses. You are deemed to have accepted these risks if you communicate with us by e-mail.



 

-----Original Message-----

**Comment by daumPostcode** [comment]
@cgrking @cgrking2 

보내주신 코드가
주석과 코드가 섞여 있고, 복사해서 에디터에 넣을시 주석이 코드를 가려버리기 때문에 코드 포맷터도 동작을 하지 않습니다. 현재 읽을 수 없는 상태입니다.

최소한 줄바꿈 처리를 해주시기 바랍니다.

**Comment by cgrking2** [comment]
var daum_zip_id = function(frm_zipcode, frm_address1, frm_address2,zip_case) {
        if (typeof daum === 'undefined') {
            alert('다음 juso.js 파일이 로드되지 않았습니다.');
            return false;
        }
  if(zip_case==='undefined')
         zip_case = 1;   //0이면 레이어, 1이면 페이지에 끼워 넣기, 2이면 새창

        var complete_fn = function(data){
            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

            // 각 주소의 노출 규칙에 따라 주소를 조합한다.
            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
            var fullAddr = ''; // 최종 주소 변수
            var extraAddr = ''; // 조합형 주소 변수

            // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
      //      if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
       //         fullAddr = data.roadAddress;

       //     } else { // 사용자가 지번 주소를 선택했을 경우(J)
               fullAddr =data.jibunAddress;
    if(!fullAddr) {
     alert('지번 주소를 선택해주세요');     
    }
    
       //     }

            // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
            if (data.userSelectedType === 'R'){
                //법정동명이 있을 경우 추가한다.
                if (data.bname !== ''){
                    extraAddr += data.bname;
                }
                // 건물명이 있을 경우 추가한다.
                if (data.buildingName !== ''){
                    extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                }
                // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                extraAddr = (extraAddr !== '' ? ' (' + extraAddr + ')' : '');
            }

            // 우편번호와 주소 정보를 해당 필드에 넣고, 커서를 상세주소 필드로 이동한다.        
         

            $('#'+frm_zipcode).val(data.zonecode);
            $('#'+frm_address1).val(fullAddr);
            $('#'+frm_address2).focus();
        };

        switch(zip_case) {
            case 1 :    //iframe을 이용하여 페이지에 끼워 넣기
                var daum_pape_id = 'daum_juso_page' + frm_zipcode,
                    element_wrap = document.getElementById(daum_pape_id),
                    currentScroll = Math.max(document.body.scrollTop, document.documentElement.scrollTop);
                if (element_wrap === null) {
                    element_wrap = document.createElement('div');
                    element_wrap.setAttribute('id', daum_pape_id);
                    element_wrap.style.cssText = 'display:none;border:1px solid;left:0;width:100%;height:300px;margin:5px 0;position:relative;-webkit-overflow-scrolling:touch;';
                    element_wrap.innerHTML = '<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnFoldWrap" style="cursor:pointer;position:absolute;right:0px;top:-21px;z-index:1" class="close_daum_juso" alt="접기 버튼">';
                    jQuery('#'+frm_address1).before(element_wrap);
                    jQuery('#' + daum_pape_id).off('click', '.close_daum_juso').on('click', '.close_daum_juso', function(e){
                        e.preventDefault();
                        jQuery(this).parent().hide();
                    });
                }

                new daum.Postcode({
                    oncomplete: function(data) {
                        complete_fn(data);
                        // iframe을 넣은 element를 안보이게 한다.
                        element_wrap.style.display = 'none';
                        // 우편번호 찾기 화면이 보이기 이전으로 scroll 위치를 되돌린다.
                        document.body.scrollTop = currentScroll;
                    },
                    // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분.
                    // iframe을 넣은 element의 높이값을 조정한다.
                    onresize : function(size) {
                        element_wrap.style.height = size.height + 'px';
                    },
                    width : '100%',
                    height : '100%'
                }).embed(element_wrap);

                // iframe을 넣은 element를 보이게 한다.
                element_wrap.style.display = 'block';
                break;
            case 2 :    //새창으로 띄우기
                new daum.Postcode({
                    oncomplete: function(data) {
                        complete_fn(data);
                    }
                }).open();
                break;
            default :   //iframe을 이용하여 레이어 띄우기
                var rayer_id = 'daum_juso_rayer' + frm_zipcode,
                    element_layer = document.getElementById(rayer_id);
                if (element_layer === null) {
                    element_layer = document.createElement('div');
                    element_layer.setAttribute('id', rayer_id);
                    element_layer.style.cssText = 'display:none;border:5px solid;position:fixed;width:300px;height:460px;left:50%;margin-left:-155px;top:50%;margin-top:-235px;overflow:hidden;-webkit-overflow-scrolling:touch;z-index:10000';
                    element_layer.innerHTML = '<img src="//i1.daumcdn.net/localimg/localimages/07/postcode/320/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" class="close_daum_juso" alt="닫기 버튼">';
                    document.body.appendChild(element_layer);
                    jQuery('#' + rayer_id).off('click', '.close_daum_juso').on('click', '.close_daum_juso', function(e){
                        e.preventDefault();
                        jQuery(this).parent().hide();
                    });
                }

                new daum.Postcode({
                    oncomplete: function(data) {
                        complete_fn(data);
                        // iframe을 넣은 element를 안보이게 한다.
                        element_layer.style.display = 'none';
                    },
                    width : '100%',
                    height : '100%'
                }).embed(element_layer);

                // iframe을 넣은 element를 보이게 한다.
                element_layer.style.display = 'block';
        }
    }












function changeAddr(){
 $('#addr').hide();
 $('#newaddr').show();
 daum_zip_id( 'zip', 'addr1_id', 'addr2', 2);
}

<tr >
             <th scope="row">주소 <a  href="javascript:changeAddr()" class="btLightG">주소변경</a></th>
             <td><div id=addr><?=stripslashes($mem[addr])?></div>
              <div id=newaddr style='display:none' >
               <input type=text size=5 name=zip id=zip placeholder='우편번호' maxlength=5 readonly>
               <input type=text size=30 name='addr1_id' id='addr1_id' placeholder='기본주소' readonly>
               <input type=text size=20 name=addr2 id=addr2 placeholder='상세주소'>
               <button onclick="changeAddrSubmit()" style='height:25px;line-height:15px;padding:2px ;border:1px solid gray;border-radius: 15px;'>변경하기 </button>
               
              </div></td>
  </tr>

**Comment by daumPostcode** [comment]
@cgrking @cgrking2 
네~ 코드 감사드립니다.

코드를 보니 제가 예전에 답글드린 autoJibunAddress 부분을 참고하지 않으셨네요;;;;......

FAQ16번이 무조건 도로명 주소를 사용하는 방법에 대해 기술하고 있지만, 도로명-지번 주소는 한쌍이기 때문에 무조건 지번만 사용하는 것도 가능합니다

=====
사용자가 선택한 값(userSelectedType)과 상관 없이 로직상 autoJibunAddress변수를 체크하고, 값이 없으면 JibunAddress변수를 이용하시면 됩니다.
지번 주소의 데이터가 셋팅되는 방법에 대해서 추가 설명 드리자면
(autoMapping을 true로 설정한 경우 - 기본값)

사용자가 도로명-지번 1:N 관계에서 메인 지번주소를 선택할 경우, 지번 주소는 autoJibunAddress에 들어가게 됩니다. 또한 연관된 지번 주소를 선택하게 되면 jibunAddress에 들어가게 됩니다.
사용자가 도로명-지번 1:1 관계에서 메인 도로명 주소나 연관된 지번주소를 선택하면, 지번 주소는 jibunAddress에 들어가게 됩니다.
사용자가 지번-도로명 1:N, 1:1 관계에서 메인 도로명주소를 선택하거나 연관된 도로명주소를 선택할 경우, 지번 주소는 address, jibunAddress에 들어가게 됩니다.
=====
위 내용은 [FAQ16](https://github.com/daumPostcode/QnA#16-사용자가-지번도로명-중-어떤-것을-선택하더라도-무조건-도로명-주소만-이용하고-싶은데-어떻게-해야되나요)번을 지번주소로 바꿔서 해석한 겁니다. 도로명주소만 선택하는 것과 다른 점은 변수만 달라졌을 때임을 확인하실 수 있습니다.

전달해 주신 코드에서는 data.jibunAddress만 이용을 하시는데, 이럴 경우 도로명-지번의 1:N관계(메인주소가 도로명 여러개의 연관주소가 지번)일 경우, 사용자가 도로명주소를 선택하게 되면 jibunAddress에는 아무런 데이터가 할당되지 않습니다.
첫 질문글에서 알려주신 주소가 이 케이스에 해당이 되며, 이때는 autoJibunAddress를 사용하셔야 합니다.

즉 항상 autoJibunAddress에 데이터가 있는지 확인을 하고, 그 다음 jibunAddress에 데이터가 있는지 확인을 해서  사용하시면 될 것 같습니다.

=====
fullAddr =data.jibunAddress; 
-> fullAddr = data.autoJibunAddress || data.jibunAddress
또는
-> fullAddr = data.autoJibunAddress !== ''" ? data.autoJibunAddress : data.jibunAddress
=====

이렇게 사용하시면 됩니다.

추가 문의사항이 있으시면 댓글 주시기 바랍니다.

**Comment by daumPostcode** [comment]
@cgrking @cgrking2 
추가로 메일로 답변을 확인하시면 댓글 변경사항에 대해서는 확인이 어려우니; 깃허브 이슈 페이지에서 확인하시는걸 추천드립니다.~ 감사합니다.
