### ISSUE TITLE
Receive"404 Not Found" response from daum.Postcode() 

### ISSUE THREAD

**Issue by LeeGrissom** [daumPostcode/QnA#989]
We started receiving a popup window response from `daum.Postcode()` that shows a 404 Not Found message.
The Javascript file we use is: `<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>`
We are running our application from inside AWS Seoul region.
Is this a known issue?

**Comment by daumPostcode** [comment]
@LeeGrissom 

Hello

It is a problem caused by IDC fire.
Currently, most of them have been restored, but some servers take time.

This problem is caused by using the legacy domain

Please use the latest domain
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js

The server has been restored.

We apologize for any inconvenience.
